name: Server CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master

jobs:
  ci:
    runs-on: ubuntu-latest
      container:
        image: node

    steps:
      - uses: actions/checkout@v2
      - name: Install & test
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASWORD }}
      - name: Docker build
        run: docker build -t cn-server .
      - name: Tags
        run: |
          docker tag cn-server ${{ secrets.DOCKER_USER }}/cn-server:${{ github.sha }}
          docker tag cn-server ${{ secrets.DOCKER_USER }}/cn-server:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/cn-server:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/cn-server:latest
